LTO_ENABLE = yes
WPM_ENABLE = yes
VIA_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = ssd1306
OLED_TIMEOUT = 0

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no

SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no

SLEEP_LED_ENABLE = yes

BOOTMAGIC_ENABLE = no
BLUETOOTH_ENABLE = no
NKRO_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
AUDIO_ENABLE = no
MUSIC_ENABLE = no

